apiVersion: v1
kind: ConfigMap
metadata:
  name: spaceforces-config
  namespace: spaceforces
data:
  SPRING_PROFILES_ACTIVE: "production"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/spaceforces2"
  SPRING_DATASOURCE_USERNAME: "postgres"
  CLOUDINARY_CLOUD_NAME: ""
  CLOUDINARY_API_KEY: ""
  CLOUDINARY_API_SECRET: "" 